[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd brand-house && npm install"]

[phases.build]
cmds = ["cd brand-house && npm run build"]

[start]
cmd = "cd brand-house && npm run start"
