import type { PageConfig } from './section-types';

let _id = 0;
function uid() { return `s${++_id}_${Date.now().toString(36)}`; }

export const DEFAULT_PAGE_CONFIG: PageConfig = {
  title: 'NorCal SBDC Brand House',
  sections: [
    {
      type: 'nav',
      id: uid(),
      config: {
        brandText: 'NorCal SBDC',
        menuItems: [
          { label: 'Brand House', href: '#' },
          { label: 'Colors', href: '/colors' },
          { label: 'Typography', href: '/typography' },
          { label: 'Templates', href: '/templates' },
        ],
        glassBg: true,
      },
    },
    {
      type: 'hero',
      id: uid(),
      config: {
        cells: [
          { src: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: '40%', zoom: 1 },
          { src: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: 'center', zoom: 1 },
          { src: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: 'center', zoom: 1 },
          { src: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: 'center', zoom: 1 },
          { src: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: 'center', zoom: 1 },
          { src: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: '30%', zoom: 1 },
          { src: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: 'center', zoom: 1 },
          { src: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: 'center', zoom: 1 },
          { src: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80&fit=crop&auto=format', posX: 'center', posY: 'center', zoom: 1 },
        ],
        cols: 3,
        rows: 3,
        colWidths: [1, 3, 1],
        rowHeightMode: 'equal',
        rowHeights: [1, 1, 1],
        gap: 6,
        aspectRatio: '16/10',
        bgColor: '#000000',
        containerRadius: 0,
        showText: true,
        heading: 'NorCal SBDC',
        subhead: 'Brand House',
        headingSize: 64,
        subSize: 13,
        textColor: '#ffffff',
        enableVignette: true,
        vignetteStrength: 60,
        vignetteSpread: 40,
        edgeDarken: 30,
        overlayColor: '#000000',
        enablePin: true,
        pinDuration: 200,
        enableInset: true,
        insetStart: 40,
        insetRadius: 16,
        skewX: 5,
        enableFade: true,
        scaleStart: 0.7,
      },
    },
    {
      type: 'manifesto',
      id: uid(),
      config: {
        editorHTML: "Don't settle for generic advice. Your business <em>deserves</em> someone who gets it — an advisor who has been where you are, who understands the terrain, who knows what it takes to turn <strong>ambition</strong> into <strong>revenue</strong>.",
        eyebrow: 'OUR MANIFESTO',
        subtitle: '',
        bgColor: '#ffffff',
        textColor: '#0a1528',
        accentColor: '#1D5AA7',
        fontSize: 48,
        lineHeight: 1.15,
        letterSpacing: -0.01,
        alignment: 'center',
        eyebrowStyle: 'mono-upper',
        maxWidth: '920px',
        fontFamily: 'serif',
        paddingTop: 80,
        paddingBottom: 80,
        grainEnabled: false,
        grainOpacity: 2,
        underlineWords: ['deserves', 'ambition', 'revenue'],
        underlineStyle: 'solid',
        underlineColor: 'accent',
        underlineCustomColor: '#3b82f6',
        ulThickness: '2px',
        ulOffset: '6px',
        ulAnimate: true,
        ulSpeed: 2,
        animType: 'stagger-words',
        animTrigger: 'on-scroll',
        staggerDelay: 40,
        animDuration: 700,
        easing: 'ease-out',
      },
    },
    {
      type: 'chapter',
      id: uid(),
      config: {
        cards: [
          { icon: 'palette', title: 'Colors', description: 'Primary palette, tints, and usage guidelines', tag: 'Visual' },
          { icon: 'type', title: 'Typography', description: 'Sofia Pro, Sweet Sans Pro, Andale Mono, and type scale', tag: 'Visual' },
          { icon: 'image', title: 'Photography', description: 'Style guidelines and image treatments', tag: 'Visual' },
          { icon: 'mic', title: 'Voice & Tone', description: 'How we write, speak, and communicate', tag: 'Verbal' },
          { icon: 'layout', title: 'Templates', description: 'Ready-to-use copy blocks and layouts', tag: 'Usage' },
          { icon: 'book', title: 'Brand Story', description: 'Our history, mission, and positioning', tag: 'Strategy' },
        ],
        cols: 3,
        gap: 16,
        padding: 24,
        bgColor: '#f5f4f0',
        cardBgColor: '#ffffff',
        cardRadius: 12,
        iconColor: '#1D5AA7',
        textColor: '#0a1528',
        headerText: 'Chapters',
        headerStyle: 'mono-upper',
        animEnabled: true,
        animStagger: 80,
      },
    },
    {
      type: 'footer',
      id: uid(),
      config: {
        brandText: 'NorCal SBDC',
        year: '2026',
        links: [
          { label: 'norcalsbdc.org', href: 'https://norcalsbdc.org' },
        ],
        bgColor: '#f5f4f0',
      },
    },
  ],
};
